### ISSUE TITLE
Issue when sync using `run auto` if playlist is enabled

### ISSUE THREAD

**Issue by fabifuu** [jbh-cloud/spotify_sync#27] opened 2023-08-05 16:28 UTC
When I enable playlist in the `config.json` file (`"enabled" = true`), there's error in `dataclasses.py` files if I run automatically.

Below is the error message that I got from console log:

```
$ spotify_sync run auto --config ./config.json
[2023-08-04 21:57:04,049] INFO      SpotifySync      : Loading config from file config.json
[2023-08-04 21:57:04,049] INFO      SpotifySync      : Script started with auto command
[2023-08-04 21:57:05,279] INFO      SpotifyService   : Fetching liked songs
[2023-08-04 21:57:14,019] INFO      SpotifyService   : Added 0 new liked song(s) from Spotify (cached:1380)
[2023-08-04 21:57:14,019] INFO      SpotifyService   : Fetching playlist songs
Traceback (most recent call last):
  File "/home/fabifuu/.local/bin/spotify_sync", line 8, in <module>
    sys.exit(cli())
  File "/home/fabifuu/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/fabifuu/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/fabifuu/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fabifuu/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fabifuu/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fabifuu/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/fabifuu/.local/lib/python3.10/site-packages/spotify_sync/__main__.py", line 48, in auto
    app.auto()
  File "/home/fabifuu/.local/lib/python3.10/site-packages/spotify_sync/cli.py", line 57, in auto
    spotify_svc.sync()
  File "/home/fabifuu/.local/lib/python3.10/site-packages/spotify_sync/spotify_.py", line 37, in sync
    liked, playlists = self._merge_playlist_songs(liked)
  File "/home/fabifuu/.local/lib/python3.10/site-packages/spotify_sync/spotify_.py", line 98, in _merge_playlist_songs
    playlist_songs = self._get_all_playlist_songs(playlists)
  File "/home/fabifuu/.local/lib/python3.10/site-packages/spotify_sync/spotify_.py", line 72, in _get_all_playlist_songs
    return self.paginator.get_songs_from_playlists(playlists=playlists)
  File "/home/fabifuu/.local/lib/python3.10/site-packages/spotify_sync/spotify_.py", line 184, in get_songs_from_playlists
    return self._to_spotify_song(response)
  File "/home/fabifuu/.local/lib/python3.10/site-packages/spotify_sync/spotify_.py", line 262, in _to_spotify_song
    s.from_api(api_s)
  File "/home/fabifuu/.local/lib/python3.10/site-packages/spotify_sync/dataclasses.py", line 107, in from_api
    song["track"]["artists"][0]["name"]
KeyError: 'artists'
```

This error propbably occurred because there is an expectation in the code that there will always be a key 'artists' present in the dictionary `song["track"]`. This key was not present, hence the `KeyError`. The function where this is happening is `from_api` in the `dataclasses.py` file.

The bug present in line 107 (`self.artist`), 113 (`self.abum`), and 126 (`self.isrc`).

The corrected code for `dataclasses.py` are presented below:
```
self.artist = (
            song["track"]["artists"][0]["name"] if 'artists' in song["track"] and len(song["track"]["artists"]) > 0 else "Unknown Artist"
            if song.get("track") is not None
            else None
        )

self.album = (
            song["track"]["album"]["name"]
            if song.get("track") is not None and "album" in song["track"]
            else None
        )

self.isrc = (
            song["track"]["external_ids"].get("isrc")
            if song.get("track") is not None and "external_ids" in song["track"]
            else None
        )
```

After I made those change, now I can download / sync the song properly without any problems, even if I enabled the playlist.

_nb: Sorry if my issue is not clear, this my first time writing an github issue._

**Comment by jbh-cloud** [comment] 2023-08-08 12:56
@fabifuu first of all thank you for a clear and concise issue. This is actually a duplicate of #24 and is related to podcasts now being served by the api. I'm am planning to resolve this a slightly different way back thanks for the contribution!

**Closed as completed by jbh-cloud** 2023-08-08 12:56 UTC
